### ISSUE TITLE
Lore suggestion for Baumi's boss

### ISSUE THREAD

**Issue by AlexDev-9000** [AngelArenaAllstars/suggestions#1]
# Original idea
Tier 1 boss, one the 4 weakest in the game.
3 phases, phase 2 triggers at 50% hp, phase 3 at 25% (or whatever ends up being the most balanced but that's the plan for now)
While fighting the boss he is always indicating a direction. All units fighting him experience a gravitational pull into that direction. While they can act fully they will always have to make time to compensate for that pull with their movement. Example: He indicates to the right. If you now try to walk to the right you'll go faster, if you go to the left you'll be slower and if you try to walk up or down then you'll actually end up tilted to the right.
To go along with this his main source of damage are paintings he draws on the ground. There'll be a line of particles that draws a pattern on the ground and after it is complete the pattern lights up and becomes active. If you touch this pattern you take damage and become disarmed. While fighting him you'll always have to be moving to avoid being pulled into these drawings.
In phase 2 he starts drawing much more complex patterns, adding to them after they have already become active. In phase 3 he'll also be throwing one of two kinds of projectiles: a fast moving one that deals X damage and a slow moving one that deals damage to you as long as you touch it.

This boss needs a theme ASAP so that the other teams can start working on it. Once you have figured something out please message me so I can notify the other teams. Also try to include some inspiration what his bossfight music could sound like and what he should look like. I'll pin this.

Edit: just to clarify, this guy does not have an auto attack

# Proposed lore
Since this guy is the less powerful dude , yet is strong enough to kill the characters and has phases, a cool concepct could be a Demon Cultist that is caught in the middle of an invocation. 

Since the characters interrupt this invocation, the demon starts to posses and merge with him, hencefore, the phases. 

Phase 1: The cultist is still himself, maybe with a bit more red in the eyes, or something alike. 

Phase 2: The demon starts possesing him, that's why he gains more powers within his own casting nature, and his aspect changes notibly, part of himself becoming already demonic, robes fussing with demonic flesh, metal twisted into horns.

Phase 3: The cultist is finally overcome, and then the demon starts using his own magic, giving a reason for the two more spells. At this stage the demon has fully consumed and merged with the cultist. Possibly leave the cultist's face in an expression of suffering in a book, or in some part of the demon's body.

**Comment by Haganeko** [comment]
Just as added info, this is for Baumi's concept (posted on writing-discussion):
"The following boss concept needs to be turned into a character:
Tier 1 boss, one the 4 weakest in the game.
3 phases, phase 2 triggers at 50% hp, phase 3 at 25% (or whatever ends up being the most balanced but that's the plan for now)
While fighting the boss he is always indicating a direction. All units fighting him experience a gravitational pull into that direction. While they can act fully they will always have to make time to compensate for that pull with their movement. Example: He indicates to the right. If you now try to walk to the right you'll go faster, if you go to the left you'll be slower and if you try to walk up or down then you'll actually end up tilted to the right.
To go along with this his main source of damage are paintings he draws on the ground. There'll be  a line of particles that draws a pattern on the ground and after it is complete the pattern lights up and becomes active. If you touch this pattern you take damage and become disarmed. While fighting him you'll always have to be moving to avoid being pulled into these drawings.
In phase 2 he starts drawing much more complex patterns, adding to them after they have already become active. In phase 3 he'll also be throwing one of two kinds of projectiles: a fast moving one that deals X damage and a slow moving one that deals damage to you as long as you touch it.

This boss needs a theme ASAP so that the other teams can start working on it. Once you have figured something out please message me so I can notify the other teams. Also try to include some inspiration what his bossfight music could sound like and what he should look like. I'll pin this.

Edit: just to clarify, this guy does not have an auto attack"

**Comment by Haganeko** [comment]
This boss has a lore already. (Havres)
