### ISSUE TITLE
Misc. Upgrades and Suggestions 2/7/17

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#117]
I WILL BE GATHERING SOMETHING LIKE THIS AT THE START OF EVERY WEEK!! IF A QUICK IDEA COMES TO MIND POST IT IN THE #design_help CHAT IN THE DISCORD SERVER

A) Consumable that gives the hero an extra backpack/inventory slot
B) Stat books like tome of knowledge but for player stats
C) A "coin" consumable that rolls a 50/50 dice that either gives the hero more damage or more attack speed
D) A "flask" alternative to the bottle that will restore the same amount of heath as the bottle but has 5 charges and will give the health instantly instead of over time as a regeneration effect
E) A "ward" that will reduce the vision of enemies when they are in the AoE, this includes wards.
F) A "grenade" that when thrown explodes after a few seconds dealing small damage in the AoE
    1) This is expanded later in the original post with a healing alternative to mana/health
G) Items that are paid for in experience.
H) A "one-time-use" blink dagger consumable... thing
I)  A "one-time-use" Crit that will guarantee a critical strike on your next hit
J) An upgrade to the courier allowing it to go invisible for a short time
--a) later expanded to give the courier an alternative evasion upgrade
K) Void Stone upgrade (like heart of tarrasque) that regenerates mana per second when mana hasn't been used
-- a) personally, I think this should be a heart side grade where you can choose to buy either more HP regen or mana regen
L) Dagon upgrade to Dagon #10
M) Item that gives negative range and attack speed in change for a lot of damage and a cleave
N) A "spell scroll" that casts one of 4-6 spells one dealing damage, one stunning/slowing, one healing, one restoring mana, one "stopping cooldown progression"
O) A "mount" giving the user flight, when the mount is killed item is removed from inv. and the player is stunned based on "the amount of trees they destroyed while flying over people"
P) Achievments
Q) Item that gives 100% spell lifesteal in exchange for 100% your armour
R) An item that has a "slider" that deals damage based on the amount of HP you sacrifice from that slider.
--a) The example gave 1% health=100 damage

**Comment by VoidsKeeper** [comment]
OK , so , I'm gonna comment in a similar way as you posted:

A)Sounds awesome if it's possible  (I'm sure it is) and if there's a limited amount for a single player's use (maybe 1-2 times). This would also make it easier to collect/combine stuff from boss fights. 

B)I don't really understand what you mean by "player stats" , but if it is something similar to the tomes from AAR , then - no.
C)Would be a nice gamble to do right before duels - I'm in for it , if the buff/debuff stats are reasonable.
D)Makes bottle lose its purpose. Either it'll cost more or have a bigger CD.  Otherwise, I don't really like it.  (But that's just me)
E)I get what you intended this to be bought and used for,  but I think that it won't work out. 1) If out of combat , people will notice this phenomenon occur and will either avoid that area or ask their team for the ward to be dewarded. 2) I don't think using something long-lasting , especially if it greatly hinders the players "eyesight", will be approved by most players. Maybe make the ward into a smoke bomb?  3) It's much easier to launch an ambush via invisibility, than use this and just lose money.
F)Idk if people would buy this item...  If it deals low amounts of damage and explodes with a delay then this would not affect the enemy(if only they aren't stunned/rooted). And if you make it cheap and spammable , then it'd just make stuff less interesting(dunno about the alternative you mentioned).
G) I believe , this was discussed before (and forgotten later...) and I'm still in favor of these type of items / costs.
H) How would this be activated? But I see what you intended. I wouldn't buy this though , cause I prefer the normal blink dagger.
I)Now this would be interesting, if it is unstackable(to avoid crit spam). PA or Earthshaker would drool over this...
J)I think it'll have it's moments,  but I also believe the normal flying courier to be more interesting  (it provokes chase and allows the enemy to slow the other team's progress)
K)Yes , please! (#I'mtotallynotamaniacalcaster ...)
L)I think that might be tooo OP with Ethereal blade...
M)I think there's already been something alike. Not sure though... I think it might work,  if the attack speed gets set to a certain amount (not %-wise)
N)So it's a "gamble scroll"? Could be fun. Could be infuriating if spammed on teammates...oh god...
O)Could lead to people being stunned forever. Also , this would remove lots of heroes qualities and require new animations for every character that can use it (and their every form). I don't like it.
P) And by that you mean...?
Q) You'd die quickly anyway without any armor , so , unless you're a Dark Seer (or someone who has something similar to Ion shell) , there's no need for a hero to use it.
R)The slider/durability idea sounds cool , but I don't think it should deal damage  (aka needs another use)

Phew...that's it for now. I'm writing from phone, so my answers might seems a bit short. Ask me questions if you want to.

**Comment by Vafnar** [comment]
The flask idea is to have a longer cool down then the bottle. In the example given it's suppose to be used as an instant regeneration item like wand, kind of an alternative to the bottle for fighters, where the bottle is meant for farming.
The slider idea at the bottom is like the Morphling 7.00 change where you can select (in percentage) how much strength/agility you have, but instead of that you would have a 100% bar take takes away your current health, anywhere from 1%-99% which would take you down to 1 health at max. If you were a 2000 health hero and you use 99% of your health (1998 hp) it would be converted into 9990 magic damage to a single target.
As was said in the post in a game you could have achievements in order to get certain items from the shop or to access different bosses. The achievements could be getting XXXX amount of gold or getting to XX level.
Spells scrolls are supposed to be either one where you buy it and it assigns the spell to the scroll upon purchase, or if that isn't possible then it is to be 5 separate scrolls that each have a unique effect.
The courier upgrade would give it the flying abilities but instead of the sprint for (sprint duration) the courier would gain a very small speed buff and give it invisibility.

Hope that clarifies some questions, and i will be doing these every Tuesday night just so no idea is forgotten, I am only gathering from the #design_help chat so if there is a suggestion post it

**Comment by Vafnar** [comment]
Oh boy....
Credit to @VoidsKeeper @chrisinajar @Melongod @Baumi @Katrix @OxTheFifth @Yahnich @KarmaticNeutral  and @h3rsh3yb3ary for these suggestions

**Comment by Haganeko** [comment]
Thank you for your valiant efforts! Edit the issue to clean up the ones which got no'd? Not delete them, just separate them from the rest.
A, C, H, I - I believe we're not adding consumables.
D - We already have a custom bottle. I don't think we're looking for more of them.
L - We already have a bunch of dagons. I don't think we need more.
P - Alternative objectives suck.
