### ISSUE TITLE
Frost demon??

### ISSUE THREAD

**Issue by erklp** [AngelArenaAllstars/suggestions#139]
I just wanted to ask if there is any ice/frost based demon. I can't find any.    Thanks

**Comment by zelding** [comment]
Ancient Apparition ?

**Comment by erklp** [comment]
Oooooooooo

**Comment by VoidsKeeper** [comment]
If you're asking about mythology , then you could say the Leviathan  (since it controls water) can control ice too. But true - there aren't that many "ice-based" demons. On the other hand there are tons of ice angels you can search up.

Also , if your question was answered , please close this issue , since it's not related to any kind of suggestion. If you want to ask questions , please use the aaa_discussion discord channel.

Once you have a ready boss mechanic(or item or boss_item , etc.), feel free to post the suggestion here ^_^

**Comment by VoidsKeeper** [comment]
And , please , use this https://github.com/AngelArenaAllstars/suggestions/commit/ea0184157763dd320303937cb71472e815999ca9
as a base for your boss suggestion

**Comment by erklp** [comment]
Thanks
