### ISSUE TITLE
[Boss Encounter] Shielded boss

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#147]
This boss is simple. It has a shield of some sort covering part of it, which blocks most damage dealt from that direction. The area covered by the shield changes with the phase.
Phase 1: Only the frontal 90 degrees (45 degrees to each side of the direction it is facing) of the boss are covered
Phase 2 (75% HP): The front and some of the sides are covered (100 degrees to each side of the direction it is facing)
Phase 3 (50% HP): Most of the boss is covered (150 degrees to each side of the direction it is facing)
The boss will turn to, and attack, the hero which has dealt most damage to it recently (before reductions). This boss is supposed to be an exercise in threat management and positioning - the heroes have to maximize how much the "good" angle of attack means, in terms of boss pit area, and be careful not to have it turn to one of their more squishy damage dealers.

**Comment by Wujekklawy** [comment]
So... It's basically punching bag for tier 1 boss? It's seems boring for me but i understand idea and what purpose it have, meaby making him like mini boss guarding entrance to other arenas will be more adequate. I don't say that is shity boss,  actually it is very good enemy to teach newbies. But this is what he is, enemy, not a boss so is say that he shouldn't be a boss. He should stand on way to bosses so i suggest put him as a guardian to arenas (and please, no respawning for he if he will be guardian,  that would make him unnoing as hell)

**Comment by lizciz** [comment]
I like this idea, and do not think it would be that boring. But I would add/change a few things.

- The shield should probably cover his whole front (like your phase 2), and absorb 100% of damage. I.e. he can only be damaged from behind.
- He should move fairly quickly, and try to reach players and bash them with the shield, dealing damage and having high probability of stun and/or pushback. But he should turn slowly, so you can get behind him.
- When someone deals enough damage, he will turn around and target them instead.

After taking some % of damage (maybe at 80%, 55%, and 30%), he gets angry and moves the shield to his back, and instead equipts a weapon. And now:
- He can only take damage from the front.
- He will be more agile, and start aggressively charging/jumping on players (with 1-2 s channel so you can get out of the way), and hunting them down, dealing high damage. If you are targeted, your only choice is to run.
- When he charges, he leaves a fire trail that deals damage if you walk on it.
- After a short while (maybe 10 seconds, or X number of charges) he calms down and goes back to having the shield at the front.
- After another short while the fire trail starts to dissipate.

Each time he enters the "angry mode", he becomes more powerful than the last time, dealing more damage, and charging more quickly.

At the end of the fight (e.g. 5-10% hp), he remains angry until he is defeated. This shoud be when he is very low hp, because when he is chargin around all the time it is difficult to damage him.

**Comment by Wujekklawy** [comment]
@lizciz but main idea is to make him noob friendly. One way or another there is needed to be some boss that will show basics of boss fighting. You trying make him as normal boss

**Comment by lizciz** [comment]
@Wujekklawy Ah, yeah that is a good point. As a first boss your original idea is better.

Possibly, you could also do your phases in reverse order.

Let the boss start out by being shielded up and tanky, but also slow. His attacks will also be fairly slow. He does not even need to right click, only do channeled shield bashes which can be avoided, but will hurt if not.

This gives players opportunity to learn the mechanics at a slow pace. 

As the phases progresses he becomes a bit quicker (perhaps shields on his sides fall off), but also less shielded, and players must adjust appropriately.

Either way, I like this boss idea :)

**Comment by Haganeko** [comment]
The boss is mostly a positioning and aggro management challenge. Many of the bosses I propose are about positioning, and this is a simpler version of it. The angles of attack mean that most of the heroes have to be positioned at the back, and the boss must be lured to a corner in order for the party to really deal any damage to it. If they can't, their poor tank will die eventually.
Also, if the boss turns on one of the damage dealers, since they will be all bunched up, they will have to start aggro management again or deal no damage.
I stand by my original design.

**Comment by l34Um1** [comment]
Yep. Had something similar in mind. Simple, works, is obvious, good. Can be put into the game like that.
