### ISSUE TITLE
[Item] Shivas + Atos

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#163]
**Active, single target**:

Roots the target + Shivas effect, but originates from the target.

**Comment by Wujekklawy** [comment]
Yyy... I don't see porpoise of that, atos is amazing gank item and you lose slow from shiva or if you want pick up someone you can't because he is usually on back line and that would be waste of slows. I dunno, for me morf of these items just bitting each other. If you want think about upgrades like that try using only one type of items like ganking with ganking or tanky with tanky but not like here ganking with teamfight. If you will go with that in mind upgrades would see natural, like atos+medalion or crismon guard with pipe etc. ;)

**Comment by VoidsKeeper** [comment]
Thanks for posting your idea  :)

So , I believe I disagree with Wujekklawy's comment. There  is ganking and teamfight  potential as a sort of weaker-type-of-winter-wyverns-ult thing. But I agree with him on the fact that this item should not originate from something connected to Atos. The Shiva must remain , since it's affect is the core of the mechanic.

But , to be honest , if I wanted to gank a team with this , I'd rather use a normal Shivas. This could be used for single target hunting (but I still see people thinking of different strats). 

I'll note this down and ask more thoroughly on the meeting.

**Comment by l34Um1** [comment]
Closed. We already have a ton of Shiva upgrades and this one isn't interesting enough to warrant another one.
