### ISSUE TITLE
[item] "Orbital-cannon-thing"

### ISSUE THREAD

**Issue by VoidsKeeper** [AngelArenaAllstars/suggestions#190]
I imagine this would be either a consumable with a long CD (in the inventory or in the shop) , a special ability for some upgraded version of boots(or radiance :3 - "sunstrike radiance")  or a boss_item ability. 

Upon activation :
*Cast range - global (or veeryy big)
*Doesn't use a lot of mana
*Casts Invoker's sunstrike , but, additionally , lights up the area from where it was fired from (revealing the caster) and leaves a medium damage DoT circle on the point of attack instead of the normal "after-sunstrike-burned-ground-texture" for 2-3 seconds.

Simple idea. If you have any questions - ask.

-VoidsKeeper

**Comment by Wujekklawy** [comment]
What is mean that DoT? Dfence of Troy? Dogeing or Throwing? Duche of Townmedia? Devil of Toilet? I have no idea...

**Comment by VoidsKeeper** [comment]
@Wujekklawy  ,  it means "damage over time" (a poison affect )

**Comment by Wujekklawy** [comment]
@VoidsKeeper i think Devil on Toilet is better anyway xD

**Comment by Wujekklawy** [comment]
Actually i don't see other purpose for it than stealing enemy camps, damage per second is not the best for killing low hp heroes,  ok i must admit that it would be good in teamfights if you have stuns or roots. So maybe lower the cast range dramatically and give it more range in aoe or damage making it teamfight item instead of "let's steal enemy camps from half of the map" :)

**Comment by VoidsKeeper** [comment]
Well , it's intended to do a variety of things (you described a few). The numbers (or ,atm, the speculations )   are mostly insignificant. I just wanted to share the idea of the mechanic ;P

**Comment by l34Um1** [comment]
We got Azazels Crossbow which is kinda similar. Not a big fan of global ranges. Closed.
