### ISSUE TITLE
[Boss Idea] Multi armed boss 

### ISSUE THREAD

**Issue by AceXS2X** [AngelArenaAllstars/suggestions#204]
Well since my first idea was way too complicated, I tried to think about a more easily understandable boss than before.

As the title says, its a boss with multiple arms...

**Inspiration**
This was based on The Hecatoncheires, a multi armed giant from Greek mythology.

**Mechanics**

My general idea is that this boss starts with 6 arms and loses his arms as you whittle him down, only leaving him with 2 arms before you kill him. Also this boss will deal less damage from his attacks as his arms fall off, however he has some abilities which are :
- He roars and massively reduces armor to all players in the arena
- He uses a forward slash that inflicts bleed ( which does around 7% of your maximum health for a period of 10 seconds)(you can see him preparing this ability)
- He roars and gives a debuff to all players in the arena that essentially acts similar to blademail ( which any damage you deal will be instantly redirected to you) and buff himself with a regen that will not stop until he has 50% of his health back and can only be paused when you deal damage to him.(only activates when he has 20% of his health remaining)

**How to Beat**
It's simple really, all of his debuffs are dispelable, thus making heroes and items with dispels very crucial in defeating this boss, especially heroes like Oracle and Abaddon with their short cooldown on their purges, or you can buy items that can purge you out of these debuffs, or you can be that guy and buy BKB (which should be renamed to boring king bar in this custom game with the custom announcer screaming shame to whoever bought it in the early stages of the game).

Another way to beat this boss which I thought about but it might be a bit to complicated is to use his fallen arms on him which will disable his regeneration

**Other**
I still haven't managed to figure out the kinks in this boss, because there's a lot of things that I haven't considered about, so I might revise this boss in the future. Also a short summary of this boss is " A melee boss that gets weaker as you fight him and has a lot of debuffs as well"

**Closing Remarks**
I apologize if this boss has a lot of problems, with certain heroes/ items I still haven't figured out the entire concept of this boss, also for your attention I give you my thanks.

**Comment by RighteousBacon** [comment]
This boss has potential. His lore is interesting, and might allow for some cool abilities and interactions.

In his current form however, there are some problems with this boss that I can see right away.

1. There are no clear phases. Bosses should have at least 3 phases, and the phases need to be glaringly different from one another.
2. The boss gets easier as the fight goes on. Bosses are supposed to become harder as you near the end of the fight, to give that sense of urgency and avoid 5 minutes long boss encounters.
3. He gets hard countered by dispels. It's good that you gave the players some outplay potential, but it's important to ensure that outplay requires skill, instead of pure foreknowledge.

I suggest you dig deeper into the lore of the boss to look for inspiration. Make it challenging, make it interesting. I for one really dig the blademail aura, but the way that you presented it makes it uninteresting. Keep refining your idea, you're already on the right track 👍

**Comment by AceXS2X** [comment]
Thanks for the suggestions, I'll probably make a revision soon, I just need some time to think about the boss, I just thought about this one as I went.

**Comment by Haganeko** [comment]
Since you have posted another version, I will assume this is obsolete. Closed.
