### ISSUE TITLE
[Boss Idea] Oil

### ISSUE THREAD

**Issue by Greenluther** [AngelArenaAllstars/suggestions#206]
A boss that can only be engaged by 2 or 3 people at a time.
At the beginning of the fight the boss sprays out a pattern of oil that only slows at first(and could be slippery) . The oil represents the arena where the 2 or 3 players have to be and if more then the amount the boss likes is in the area of the oil the boss lights the oil on fire and transitioning in to an enraged flaming state.
Additionally during the oil stage of his fight the players in the arena could have a spark status affect that could cause the oil to ignite if they get to close to another player or cast a spell.

**Comment by Haganeko** [comment]
This is an interesting mechanic, but it needs a context which might make it work.

**Comment by Wujekklawy** [comment]
Actually why i not thought about it? It would make pretty nice hero in fire theme :).  Just give him that oil, but instead of slipery it would slow, give him skillshot that aply burn and if burned enemy would standing on oil it will give less slow but start dealing damage over time, maybe also give him modified auto attack to make him more unique and different from other heroes. (if i don't have one with that already, i can't check and i don't remember, too many of them) i will check that ASAP (it should be some day :/)

**Comment by Wujekklawy** [comment]
I made hero with this abbility. Do you want to share it to you?

**Comment by Haganeko** [comment]
This has gone nowhere, Closed,
