### ISSUE TITLE
Easy boss fight. Fight idea

### ISSUE THREAD

**Issue by VoidsKeeper** [AngelArenaAllstars/suggestions#22]
Easy boss fight idea(Hide-and-seek):

Info: 

The arena is small (compared to the other ones) and covered in trees (overflowing , actually). This boss is squishy and mainly remains camouflaged as a tree. He moves from time to time(often) revealing himself (like the Monkey King disguise). To undisguise the boss you either hit it with an AoE ability or hit the moving tree (cleave works too) (if it's possible to make all the trees targetable , it'd be great). After being revealed the boss silences the attackers with a spell similar to  Riki's "cloud". The boss fights for some time before tp'ing away and disguising itself again.

Spellset:
1) While the boss is disguised , he constantly drains mana% and hp% from the players.

2) At any time/shape the boss may randomly root the attackers (Treant protector's ultimate with ag's)

3) When undisguised  the boss may suddenly surround itself with trees (Nature prophets trap ability ) and then will use 2 Earthshaker fissures(but made out of trees) in a cone like shape towards a random hero (Only the heroes inside the cone can attack the boss head-on. Others should either use spells or long-range attacks , etc.

-------

Well , that's basically it. I don't really know how to make the boss's abilities be nice , but the original idea was that the boss hides in trees and attacks whilst hiding.

**Comment by warpdragon** [comment]
So essentially he has 2 modes: Stealth and Fighter.  While he's stealth he essentially does nothing except run around and occasionally root people (which doesn't actually accomplish much).  Once he's revealed he starts kicking everyone's ass.  It seems like the whole "hide and seek" aspect of the hero is largely just making this fight take longer than it needs to, although I like the concept a lot, it needs some refinement.  
_______________________
Ideas for changes to stealth:
* He stands still for **x** seconds or until a player targets him. Then he runs away. You then have **y** seconds to break his disguise or he teleports away. 
* Upon teleporting away he leaves **n** treants behind to fight you. These treants create action during the stealth phase and also distracts players from trying to find the boss. The more dangerous the treants, the harder it will be for players to concentrate on finding the boss. The treants could even have Misha's root or something to increase the difficulty.
* If players don't find him after **z** seconds, he casts overgrowth. Players standing near trees are rooted and the boss then breaks stealth and becomes a fighter, targetting the most vulnerable nearby hero.
_______________________
Ideas for changes to fighter: 
* I like the idea of using a Tree/Fissure trap, but what about this: Circle trap - creates a circle of trees around him with radius=300, trapping nearby heroes. At the end of the spell the trees could turn into treants. Give him Nether Swap and flying vision in case he wants to swap out, trapping another hero to be devoured by treants.
* Also Maybe instead of Riki cloud he has Orchid and Desolator (like Furion).
* Give him some form of soft area crowd control (possibly similar to fissure trap, but maybe something else) to increase the effectiveness of his and his treants' attacks.
* Give him a super epic attack spell that players have to avoid (possibly the fissure trap but maybe something else).
* At the end of the fighting phase he teleports back into stealth.
_______________________
Ideas for treants: 
* When a treant dies it has a % chance to plant a new tree.
* Treants that don't die after a period are detonated, doing damage.
* 1 out of every 10 trees is unique, maybe having mana burn, Misha root, or Fury swipes.
_______________________

**Comment by VoidsKeeper** [comment]
Warpdragon , you're amazing. This sounds so cool from you XD 
Thank you very much

**Comment by VoidsKeeper** [comment]
Note to whoever reads this comment. I cannot edit this post via phone , so FYI , I'd like some of my mechanics be replaced by what Warpdragon suggested

**Comment by l34Um1** [comment]
A boss that hides is noted. Closed.
