### ISSUE TITLE
[Hero balance] Monkey king

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#241]
After seeing Baumi's video on MK, I think we realy should consider updating Jingu mastery.

*Reason*: it will be useless outside teamfights.

*Possible options*: just make it trigger on neutrals too, also
- stacks damage on monkey king, after a certain stacks triggers the lifesteal
- against neutrals severely reduce the damage it gives
- just make it passively increase damage against neutrals
- I'm sure there are other possibilities

**Comment by Wujekklawy** [comment]
that would ruin ballance of hero, "get stacks on creeps and gank, get stacks and gank", that would be mk farming with will be evry game if changeing that abbility.

**Comment by RighteousBacon** [comment]
To be fair, moving any hero from regular dota to aaa will screw up the hero's balance. I believe that's part of the reason why Baumi keeps yapping on about pushing for version 1, because at least then we'll know how much we derailed from the Will of Icefrog.

On the issue of MK, maybe make it so the ability stacks separately (and differently) on neutrals, much like what's been done to cleave.

**Comment by Wujekklawy** [comment]
@RighteousBacon can you also do something with flack cannon? it makes gyro op in earlygame, always

**Comment by zelding** [comment]
> can you also do something with flack cannon? it makes gyro op in earlygame, always

We shall see how OP is he

**Comment by Haganeko** [comment]
I am unsure MK is still an issue. Valve has nerfed him HARD. Closed, for now.
