### ISSUE TITLE
Vafnar's Weekly Record 3/3/17

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#245]
All ideas were taken from the #design_chat from the discord server.
A) Shell Game Boss
B) Slot Machine Item/Ability that drains money for damage/healing
C) Addons for heroes/bosses like Gyrocopter's Aghnahim scepter that when the hero is killed drops the addon as a "consumable" item that is put onto the hero
D) Boss more powerful during Even/Odd minutes
E) Item that allows ganking by going under the map allowing passage through unpassable places
F) Dragon Mini-boss in order to get to large boss
G) Item that burns like radiance, but the closer you get to them the less it hurts
H) A dodge roll button
Suggestions from @zelding @warpdragon @Kartrix @Haganeko @chrisinajar **Myself** @Baumi

**Comment by Haganeko** [comment]
I posited my problems with A - feels like a luck based encounter. Same with B.
E sounds like a smoke.
I think G is already in? It was proposed some weeks ago, at least.
H is like the dash core thing Baum proposed. We need to remember this is not DS.

**Comment by RighteousBacon** [comment]
I want to add some of my opinions as well:
D seems a bit forced. Those kinds of see-saw power struggle already exists in dota due to heroes being inherently imbalanced during different phases of the game. I don't know about aa2, but I don't like the idea of enforcing a certain rhythm to a game, hope that made sense.
F doesn't sound interesting, it's just 2 bosses.

**Comment by Wujekklawy** [comment]
H sounds like flash in League, and there also evryone take it ;) anyway, i submited like 6 posts and they was not checked at all, they sit here like two weeks now.

ps. when you will be want hero submitions, i have "few" heroes alredy tu submit ;)
