### ISSUE TITLE
Any Tier Boss idea. The Shadow.

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#25]
The idea of this boss is that it should by no means be fair, in a way that the boss will not try to fight fair , he will use tricks and underhanded tactics to gain advantage. He is supposed to be fairly  weak in terms of HP and armor, but will not let you hit him for too long. He should have higher then usuall Attack speed, since some of his abilities will be linked with it.

So, the begining of a fight should be non-standart, when your team walks in the boss pit, he is not there, in fact it is completely empty and when someone gets in the middle of a pit, the smoke appears and the boss jumps on a closest target to the center, marking him with unpurgable debuff  **_Marked_**, this target will be high priority for some abilities. After the taget is **_Marked_** boss aggroes on that target and starts to hit him, but the aggro can be shifted if you stun the boss and then the aggro will be reset on a closest unit to the boss. When **_Marked_** taget dies, someone else randomly becomes **_Marked_**.

**Spell 1**: The boss  always has a buff on him which tells what effect his next finishing move wil do, each Xth attack(need to be balaced, depending on attack speed, about each 7-9 seconds finishing move need to proc)  will be finishing move. Buff include: ( Bash a targer for 3 seconds; Apply Rupture; Apply 70% slow with overtime gets weaker, but only if you move, when you stand it gets stronger again; 30% healing decrease; Attacked target will implode after 7 seconds, pushing all nearby allies away; Makes next boss's ability which hits that targer to act as if you are marked(lasts 30 seconds). And those buffs should rotate in predictable manner so you would be able to tell what he will cast next.

**Spell 2**: The boss dissapears for 5 seconds, after 3 seconds , one of 4 sides of **_Marked_** target will be highlited , meaning that when boss appears , he will charge at **_Marked_** target from that side. When boss appears he will be quickly dashing to  the **_Marked_** target  from the side which was highlited , damaging , stopping and aggroing on the first hero which he encounters on his way , if this hero is **_Marked_** , he will take 10000% more damage and be stunned for 7 seconds.

**Spell 3**:The boss  makes a quick side step , dislocating all progectiles and throw a knife in the spot where **_Marked_** targer stands, if **_Marked_** target is hit, the target is pinned in place until the knife is destroyed ( has some HP, shouldn't be 3 shot by the **_Marked_** target) and also get debuff, **blood scent**, which deals moderate DoT. If the knife drops on the ground, the boss teleports to the knife ,makes a quick spin damaging all nearby units and applying physical DoT, then starts to sprint towards **_Marked_** target for 10 seconds, while sprinting the boss has 50% increased attack speed. If the knife hits another hero , who is not **_Marked_** then this hero gets **blood scent** but is not pinned and knife stays in the ground, can still be killed.

**Spell 4**:The boss smells target who has **blood scent** on them,  then the boss teleports behind them applying strong bleeding,physical DoT,but doesn't last long, if **_Marked_** target also gets this DoT, then it won't dissapear until the unit is healed to full.

At about 70% HP the boss gets into **Phase 2**.

In **Phase 2** all spells get buffed.

**Spell 1**: THe boss gets finishing move more often.

**Spell 2** works the same, but together with the boss an illusion will appear on the opposite side and also sprint to the **_Marked_** target, it deals 50% less damage to all non-**_Marked_** targets.

**Spell3**: The boss always teleports to the knife and spins, also and illuson appears at each other knife which already lies on the ground and also spins, dealing 70% of the damage ot all non-**_Marked_**, targets.

**Spell 4**: Together with the physical DoT , magical damage DoT applyed for the same duration, **_Marked_** target also gets healing debuff for 50%.

At 30% HP the boss gets into **Phase 3**.

In **Phase 3**:

**Spell 1** is still showing buff which wil be applyed in the next finishing move, but now it can lie and instead of predictable pattern it randomises.

**Spell 2** is still showing indecators,but they also don't have to be true, the dirctions are randomised for boss and the illusion.

**Spell 3** the boss is throwing knifes at each player in the boss pit.

**Spell 4** the boss also stuns targets for 1.5 seconds.

If you are still reading so far, then thank you  for your attention and have a nice day.

**Comment by warpdragon** [comment]
* Having the boss only appear if they walk into the center of the arena is a really neat idea. We just need a good way to coerce players into walking into the center. Maybe a free bounty rune or a trail of mangos leading there. Or better yet they have to go there in order to unlock an objective without realizing the Trickster is guarding it.
* "The idea of this boss is that it should by no means be fair." but remember you have to give players reliable ways of countering these "unfair" moves or else you risk creating an unenjoyable boss fight. 
* I can't tell from the description but does the "Mark" ever change heroes without those heroes dying? If not I would suggest implementing one or else you'll have players suiciding on purpose just to switch marks or other some such nonsense. What if it switched heroes once or twice each phase based on RNG?
* Try and avoid exceedingly long stun duration, maybe replace with something equally unfair but more fun for players.
* Idea: What if bleeding a player also healed the boss when the bleeding player moves like rupture.
* Idea: What if you replaced his dash mechanic with a "Skewer" type charge that applies "rupture" if it skewers a marked unit.

**Comment by Valiens** [comment]
Well, by unfair I meant that it is a fighting style of a boss, by means of disjointing projectiles and dissapearing all the time. 

About stun, yes I just wanted to highlight that playstyle of "protect the carrier" the **Marked** unit. Like , the **Marked** target has to cooperate with the team and together they work towards blocking boss's tricks, so stun can be replaced by heavy debuff, like bleed DoT or may be some other form of CC witch is not so boring, may be something like moderate slow witch grows if you try to move and decrease when you stand.  
The problem with switching is that I supposed that the team ought to deliberately make a choice whom to mark, because the **marked**  target has a lot of pressure on them, I really don't think that randomizing it would be benefitial, but may be through some sort of predictable cast it is possible to change the mark up, but to be honest it is up to debate, since again the point of a fight is to make the **Marked** target someone who needs you akin to bodyguards, so it can be argued against swithching roles up or not.

Healing boss while moving with bleed from **spell 3** can be interesting and certantely can e considered, may be as addition from **Phase 2**.

As per dash, I really just meant that Boss becomes sort of a projectile which has to be blocked, so any type of movement should be fine as long as it's tragectory is predictable.

Thank you on your imput, please feel free to comment on any of my ideas, I am open to the debate.

**Comment by warpdragon** [comment]
I don't like the mark being permanent and based on which hero was nearest center. It doesn't make sense and it's one of those 4th wall breaking spells that just feel icky. "The players know the mechanic and sent in ursa/bristle/axe/misha first and the 'Trickster' god just plays into it" What kind of Trickster is he if he is pwned by his own mechanic!? Then the team that doesn't know this one very trivial detail (sending the right player to the right spot at the right time before the fight) has NO CHANCE to defeat the boss, not because they're bad, but because they sent in skywrath or crystal maiden first!
This needs to be changed. It's the one ugly detail that's ruining an otherwise perfectly reasonable concept.

**Comment by l34Um1** [comment]
Hiding idea is cool. Can be used with better mechanics though. Closed.
