### ISSUE TITLE
{Item/Mechanics} Grenade suggestions

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#262]
For this post you must know the follwoing:
Post #248 where i define shielding
The AoE of 90% of the grenades is only 300-500 units
The Definition of a Grenade: 
1. a single use item that has a very powerful effect, but can effect allies.
2. a rechargeable item that has an extensive cooldown, but has a very powerful effect and can effect allies.

In any case here are some suggestions by:
@InNOutKing, @TheDeadj, @Kartix, Me, as well as a few ToR devs.
A) Heal bomb: Heal all targets in the AoE for 150 health, then give them 1% regeneration for Health
B) Mana Bomb: Give all heroes in the AoE a Shield for their mana pool 
C) Armour Bomb: Give all allies a 500 health shield
D) Standard Grenade: Lob a bomb dealing 333 damage to all targets and destroying obsicals
E) Oracle Grenade: Give vision in a 1500 unit radius to all allied heroes for 5 seconds, during the duration the radius closes in
F) Flash Bang: Blind all enemy heroes giving them a 35% miss chance and all allied heroes a 10% miss chance for 10 seconds, for allies 5 seconds.
G) Wrath Bomb: Give all allies 33% additional damage in all ways
H) Ability bomb: Cast a random spell targeted to all heroes in the AoE, the spell must be owned by a hero participating in the game.

**Comment by Wujekklawy** [comment]
Actually A is weaker mek (early one) B  is making Dusa abbility practicly  useless.  C  sounds like guardian   D sounds not much of good item. E is useless taking in mind that instead of fortify will be button that do basically same thing.  F i dunno, it's just wierd portable techies, everyone will hate you  if you buy it. G i don't see  point of it, it just make teamfights 33% faster.  H is it miracle staff not already accepted?  


Ps, i not posting it to hate you,  some of them would work as Acktive abbility for buffs for some items like mek or guardian. But not rly as a stand alone consume items or a new one (they are most of this stuff already in game as items).

**Comment by Haganeko** [comment]
A: Healing Mines is a thing.
B: Sounds complicated, to introduce a whole complex mechanic for one item.
C: Same as above.
Either way, I think we aren't doing consumables,

**Comment by Haganeko** [comment]
As I said in April, we're not doing consumables.
