### ISSUE TITLE
[Question] Need Abbility.

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#274]
For some time i have a hero in mind but I'm not able to make 4th (actually 5th if counting subskill of ult) abbility so haveing at least occasion to check github (still need to w8 for pc sadly, reason why i not even tried to get in to dev ;])  i ask for suggestions cuz I'm basically stuck with he and making tree without Abbilities is pointless (cuz specification of my trees). For now i have this:

>Melee, agi.
>
> Abbilities 
>---
>
> [Q]  Grants 100% lifesteal for x attacks for x seconds.
>
> [W] Create shield that block 100% damage from any abbility after reducktions, duration ~3s. If destroyed give mana, amount based on damage blocked.
>
> [E]
>
> [R] Reviles all enemy heroes [give vision like old track], enemy vision is reduced, enemy lose all sheared vision,  can only see what a hero see (players only can see what their own here see, cant see what other player from same team see, also wards/buildings also not grants additional vision for players.(evry unit /building vision is reduced to vision of Itself)
>
> [F], [Only when R is acktive]. Charge on target, around 1350 ( Barathrum max speed is 1250), Reduce armor of target. Visual indicator who is being targeted, visible for both teams.

So I'm not decided what to give him that would work with he  that could give him carry potential without making him Ursa of 1v1 giveing enemy chance to kill him  in 1v1. So any burst damage i automatically will  be declined.  Critical strike also.

**Comment by Vafnar** [comment]
I imagine this hero as a kind of unique blind hero with a special mechanic only available to this hero, due to this I would alter the [Q] ability to be more like: Grants 100-200% lifesteal against Blinded targets, for X seconds, as a result of this general "theme" of a hero I would make the [E] a general blind to help enable the [Q] ability, which is where I came up with this:
[E] Blind a target and reduce his vision to 2/5 what it normally is and remove shared vision for a short-medium duration. 
In addition to this some feedback about the [W] ability does not really fit, considering that the [Q], [R] and in my case the [E] ability all combo well with each other, but I don't really see the [W] mana refund coming into play without at least some sort of cooldown reduction. An evasion based skill seems more reasonable to me in the case of this hero.
Also if I were you I would pick up the game Heroes of the Storm, as this closely resembles two characters combined- Illidan and Cassia- and if your ever look for ideas that game can be very inspirational.

**Comment by Wujekklawy** [comment]
@Vafnar 
- i played dota 2, dota 1(few matches i was curious), SMITE. HotS, League of Lesbians(Legends), Paragon(optimalization is shit in this one) and some mobile ones: mobile legends,  vainglory(probably best one for now mobile moba) and strike of kings (they changed name for some reason) so... Yea... about inspiration you don't need to worry :)

- About hero, [Q] and [W] work pretty well with [R1] ( [F] ), also pretty good idea ;) not exactly what I was looking for cuz i need only one abbility,  i recommend you write somewhere your idea :) If you want lifesteal on blind targets better go with something like this 👍 

>[Q]  small aoe,aply blind on enemy /neutral. Grants lifesteal and spellsteal vs blended targets.

>[W]  leaps forward dealing aoe damage (or something else that deals aoe damage) 

- Actually i thinked a lot about whay abbility i should give him,  cleave(too lame), splash attack (could be ok but it's not enough), Double strike that aply some effect (too much 1v1 situation,  i need something for teamfights),  critical strike ( too much 1v1), split attack (lame and just not fit), bash/stun (too close to Barathrum and too much 1v1), smoke that removes allay vision and reduces it (too op for abbility,  more of a ult thing), evasion (already have defense abbility), return (not very tanky), counter that aply effect (too much of e 1v1) slow (too much 1v1)  i think i will go for aura if someone will not come with great idea(or something that will give me glimpse of it)

**Comment by Wujekklawy** [comment]
i at last thought about abbility that is perfeckt for that :) CLOSED
