### ISSUE TITLE
[Layout] new GUI button

### ISSUE THREAD

**Issue by Sam-Kruglov** [AngelArenaAllstars/suggestions#306]
Button text: "**I've just seen a bug!**" or whatever shorter
_When pressed, saves logs and asks the user for input._ When the text box is not empty "submit" button appears. Maybe there is a drop-down menu with options like "in the last min", "in last two mins" etc with default as "in the last min" so you know how many logs you need to save.
I bet 90% of bugs don't get reported cause the users are lazy, and using that way it takes the least effort possible. Like, I wouldn't go to GitHub every time.

**Comment by Wujekklawy** [comment]
Most bugs are not reported because i can't play gamemod :) i'm such a bitch in terms of reporting stuff xD i would report evry littlest glitch. Even that small rock dissappear when you are in 200 units away looking on your hero in preview view haveing opened settings on third pad in advanced options haveing cursor between third and fourth option in second and third row.  (ps. That is example).

But seriously great idea, i think it also should apire after match. People are lazy pricks. And I'm the laziest of them all.
>and probably the mightiest ;D

**Comment by Haganeko** [comment]
We are implementing a logging system, which is something of an improvement over this. Thank you for the suggestion!
