### ISSUE TITLE
rework tinker

### ISSUE THREAD

**Issue by tiny-pangolin** [AngelArenaAllstars/suggestions#399]
The idea has been put out about tinker being reworked. below are three rework ideas 

1) change rearm to be a charged based ability so he can only rearm every so often like a low cool down refresher orb. Tinker could also be allowed to cast it on other heros for multiple charges.

2) change rearm to reduce cool down for tinker in a similar method to octarine core 

3) make rearm an aura that accelerates cooldown ex if a hero stands in the aura for 1 second 1.5 seconds to reduced from spell and item cool downs.

**Comment by Wujekklawy** [comment]
Dont forget that Tinkers ult is essencial part of a hero, if you change how his ult work it will not feel like same hero anymore, i would add number 4. Give his ultimate like 3 stacks, as for lvl 3 and above, stacks would regenerate lets say after 15s, that dont interrupt farming as mutch but reduce amounts of cancer he can provide in teamfights.   And its very easy to implement and understand for players since a lot of ifrent heroes use them
