### ISSUE TITLE
[Concept] creep drops

### ISSUE THREAD

**Issue by Sixtrings** [AngelArenaAllstars/suggestions#57]
Instead of dropping an item from the shop, what if they dropped instant consumed items? Like the bags of gold and the potions in the Dark Moon event, but can also drop exp shards and movement speed potions (and anything else that makes farming easier/ more efficient).

**Comment by yommi1999** [comment]
I concur. It is frustrating when there are all these items that just lie there. 95℅ of the time I don't pick up the items. Making them consumables or just gold bags feels better.

**Comment by warpdragon** [comment]
The Dev team affirmed at the meeting last weekend that they don't want to introduce any new early game items. Although I really do like that this mechanic seeks to reduce the "drop overload" seen in so many AA games and likewise in many Dungeon Crawlers (PoE and Diablo3).

Maybe they'll consider it.

**Comment by warpdragon** [comment]
Seems really cool. I also would like to see less "drop vomit". However, I have a feeling this issue is currently being addressed in other ways. I have a feeling the loot system they're rolling out is going to be really sophisticated. Check out https://github.com/AngelArenaAllstars/aaa/commits/master

**Comment by Haganeko** [comment]
Implemented as Bottles.
