### ISSUE TITLE
Idea for difficulty settings regarding bosses

### ISSUE THREAD

**Issue by brainfart123** [AngelArenaAllstars/suggestions#79]
When selecting a higher difficulty (e.g. hard mode) remove ground highlights of bossattacks and/or reduce windup times of attacks

**Comment by Haganeko** [comment]
I'm not sure we have difficulty settings, just length ones. Are you suggesting we do? Voting for those would have to be carefully managed, so that more experienced players don't outvote newer ones and make their experience horrible.
Also, wouldn't this reduce the skill cap, by making the game more random (as the players have less information)?

**Comment by brainfart123** [comment]
You do have a point there. But that gave me another idea: How about client sided difficulty settings: When you pick hard mode the game will be harder only for you: So it might remove the mentioned highlights and/or change the animations that only you see so there is less reaction time for you. Maybe even apply some permanent debuffs like less stats, lower proc chance or more expensive items or bosses doing extra things to heroes with the hard mode debuff.

The idea is that someone who is relly good may want to handicap himself and/or to get a real challenge. That might be something for Baumi if he wants to play with people, that arent that good he could just handicap himself. The only problem I see here is that there is no obvious reward, other than the challenge.

Would that idea be worth another issue?
